<table border='1'>
    <tr>
        <td>Username</td>
        <td>Email</td>
        <td>Address</td>
        <td>Phone</td>
        <td>Gender</td>
        <td>Delete</td>
    </tr>
    <?php
        foreach($listUser as $listUs){
            echo "<tr>";
            echo "<td>".$listUs['username']."</td>";
            echo "<td>".$listUs['email']."</td>";
            echo "<td>".$listUs['address']."</td>";
            echo "<td>".$listUs['phone']."</td>";
            echo "<td>".$listUs['gender']."</td>";
            echo "<td><a href='/all/cart_with_mvc/index.php?module=admin&controller=user&action=delete&id=".$listUs['id']."'>Delete</a></td>";
            echo "</tr>";
        }
    ?>
</table>
<a href="/all/cart_with_mvc/index.php?module=admin&controller=user&action=insert">Insert User</a>