<?php
    session_start();
?>
<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="content-type" content="text/html" />
	<meta name="author" content="web24h.com.vn" />
	<title>Untitled 8</title>
    <meta charset="utf-8" />
    <style>
        ul{
            margin: 0px;
            padding: 0px;
            list-style: none;
        }
        ul li{
            width:  300px;
            border: 1px dashed #ccc;
            padding-bottom: 5px;
            padding-left: 5px;
        }
        ul li h3{
            font-size: 14px;
            text-align: left;
        }
        ul li a{
            text-decoration: none;
            color: #878787;
        }
        ul li a:hover{
            color: red;
        }
        p.cart{
            border: 2px dashed orange;
            width: 280px;
            padding: 10px;
        }
    </style>
</head>
<body>
    <p class="cart">
        <?php
            
        ?>
    </p>
    <ul>
        <?php
            if(isset($listProduct) && $listProduct != null ) {
            foreach($listProduct as $list){
        ?>
        <li>
            <h3><a href=""><?php echo $list['pro_name'] ?></a></h3>
            <p>Giá: <?php echo number_format($list['pro_price'],0). 'vnđ'; ?></p>
            <p><a href="/smartosc/FRESHER05/day4/default/cart/insertcart/<?php echo $list['pro_id']; ?>">Mua hàng</a></p>
        </li>
        <?php }} ?>
    </ul>
</body>
</html>