<meta charset="utf-8" />
<style>
    label{
        float: left;
        width: 100px;
    }
    input{
        margin-bottom: 5px;
    }
    .error{
        color:red;
    }
</style>
<?php
    
?>
<form action="" method="post">
    <label>Full name</label>
    <input type="text" name="txtname" value="<?php echo isset($_POST['txtname'])?$_POST['txtname']:"$name" ?>" />
    <span class="error">
        <?php echo isset($error['errorName']) ? $error['errorName'] : ""; ?>  
    </span>
    <br />
    <label>Email</label>
    <input type="text" name="txtemail" value="<?php echo isset($_POST['txtemail'])?$_POST['txtemail']:"$email" ?>" />
    <span class="error">
        <?php echo isset($error['errorEmail']) ? $error['errorEmail'] : ""; ?>  
    </span>
    <br />
    <label>Address</label>
    <input type="text" name="txtaddress" value="<?php echo isset($_POST['txtaddress'])?$_POST['txtaddress']:"$address" ?>" />
    <span class="error">
        <?php echo isset($error['errorAddress']) ? $error['errorAddress'] : ""; ?>  
    </span>
    <br />
    <label>Phone</label>
    <input type="text" name="txtphone" value="<?php echo isset($_POST['txtphone'])?$_POST['txtphone']:"$phone" ?>" />
    <span class="error">
        <?php echo isset($error['errorPhone']) ? $error['errorPhone'] : ""; ?>  
    </span>
    <br />
    <label>Country</label>
    <input type="text" name="txtcountry" value="<?php echo isset($_POST['txtcountry'])?$_POST['txtcountry']:"$country" ?>" />
    <span class="error">
        <?php echo isset($error['errorCountry']) ? $error['errorCountry'] : ""; ?>  
    </span>
    <br />
    <label>Gender</label>
    Male&nbsp;<input type="radio" name="gender" value="1" <?php if(isset($_POST['gender'])&&$_POST['gender']==1) echo "checked";
                                                                elseif ($gender==1) echo "checked";
                                                                else echo "";
                                                             ?>  />
    Famale&nbsp;<input type="radio" name="gender" value="2" <?php 
                                                                if(isset($_POST['gender'])&&$_POST['gender']==2) echo "checked";
                                                                elseif ($gender==2) echo "checked";
                                                                else echo "";
                                                            ?>  />
    <span class="error">
        <?php echo isset($error['errorGender']) ? $error['errorGender'] : ""; ?>  
    </span>
    <br />
    <label>&nbsp;</label>
    <input type="submit" name="btnok" value="update" />
</form>
<?php
    ?>
